src/main/java/it/gov/pagopa/payhub/auth/controller/AuthController.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/utils/JWTValidatorTest.java

fix: Api-auth-token

---

.devops/code-review-pipelines.yml

fix code-review trigger condition

chore: Fix code-review trigger

---

build.gradle.kts
openapi/p4pa-auth.openapi.yaml
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/exception/AuthExceptionHandler.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/exception/AuthExceptionHandlerTest.java

feat: P4ADEV-389 new openApi

---

src/main/java/it/gov/pagopa/payhub/auth/controller/AuthControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthService.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenService.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateTokenService.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateTokenServiceTest.java

fix: P4ADEV-403 passing parameters from Controller to Service

---

src/main/java/it/gov/pagopa/payhub/auth/exception/AuthExceptionHandler.java
src/main/java/it/gov/pagopa/payhub/auth/exception/custom/InvalidExchangeClientException.java
src/main/java/it/gov/pagopa/payhub/auth/exception/custom/InvalidExchangeRequestException.java
src/main/java/it/gov/pagopa/payhub/auth/exception/custom/InvalidGrantTypeException.java
src/main/java/it/gov/pagopa/payhub/auth/exception/custom/InvalidTokenIssuerException.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateTokenService.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateTokenServiceTest.java

fix: P4ADEV-394 validate postToken request params

---

openapi/p4pa-auth.openapi.yaml
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthService.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/AccessTokenBuilderService.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenService.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateExternalTokenService.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateExternalTokenServiceTest.java

fix: P4ADEV-406 refactor service result to controller

---

src/main/java/it/gov/pagopa/payhub/auth/exception/AuthExceptionHandler.java

fix: P4ADEV-427 fix error logging

---

openapi/p4pa-auth.openapi.yaml
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/exception/AuthExceptionHandler.java
src/main/java/it/gov/pagopa/payhub/auth/exception/custom/InvalidAccessTokenException.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthService.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserServiceImpl.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthServiceTest.java

fix: P4ADEV-445 userInfo controller2service

---

src/main/java/it/gov/pagopa/payhub/auth/service/TokenStoreService.java
src/main/java/it/gov/pagopa/payhub/auth/service/TokenStoreServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceImpl.java
src/test/java/it/gov/pagopa/payhub/auth/service/TokenStoreServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceTest.java

fix: P4ADEV-446 caching AccessToken String

---

openapi/p4pa-auth.openapi.yaml
src/main/java/it/gov/pagopa/payhub/auth/exception/custom/InvalidTokenException.java
src/main/java/it/gov/pagopa/payhub/auth/service/TokenStoreService.java
src/main/java/it/gov/pagopa/payhub/auth/service/TokenStoreServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/IDTokenClaims2UserInfoMapper.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateExternalTokenService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/utils/JWTValidator.java
src/test/java/it/gov/pagopa/payhub/auth/service/TokenStoreServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/IDTokenClaims2UserInfoMapperTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateExternalTokenServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/UserServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/utils/JWTValidatorTest.java

fix: P4ADEV-443 userInfo businessLogic

---

src/main/java/it/gov/pagopa/payhub/auth/configuration/RedisConfig.java
src/main/java/it/gov/pagopa/payhub/auth/service/TokenStoreServiceImpl.java
src/test/java/it/gov/pagopa/payhub/auth/configuration/RedisConfigTest.java

fix: P4ADEV-447 fix UserInfo serialization

---

postman/p4pa-auth-E2E.postman_collection.json

chore: P4ADEV-444 userInfo testPostman

---

postman/p4pa-auth-E2E.postman_collection.json

fix: P4ADEV-453 logout test Postman

---

postman/p4pa-auth-E2E.postman_collection.json

fix: P4ADEV-456 fix test postman message post logout

---

postman/p4pa-auth-E2E.postman_collection.json

chore: P4ADEV-517 updating postman environment

---

helm/values.yaml
src/main/resources/application.yml

chore: P4ADEV-507 access organization mode configurable

---

postman/p4pa-auth-E2E.postman_collection.json
src/main/java/it/gov/pagopa/payhub/auth/config/MongoConfig.java

fix: P4ADEV-508 configuring mongo

---

src/main/java/it/gov/pagopa/payhub/auth/model/Operators.java
src/main/java/it/gov/pagopa/payhub/auth/model/Users.java

chore: P4ADEV-509 Users Operators entities

---

src/main/java/it/gov/pagopa/payhub/auth/config/MongoConfig.java
src/main/java/it/gov/pagopa/payhub/auth/model/Operator.java
src/main/java/it/gov/pagopa/payhub/auth/model/User.java
src/main/java/it/gov/pagopa/payhub/auth/repository/OperatorsRepository.java
src/main/java/it/gov/pagopa/payhub/auth/repository/UsersRepository.java
src/main/java/it/gov/pagopa/payhub/auth/repository/UsersRepositoryExt.java
src/main/java/it/gov/pagopa/payhub/auth/repository/UsersRepositoryExtImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/IamUserRegistrationService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/registration/ExternalUserIdObfuscatorService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/registration/FiscalCodeObfuscatorService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/registration/UserRegistrationService.java
src/main/java/it/gov/pagopa/payhub/auth/utils/Constants.java
src/test/java/it/gov/pagopa/payhub/auth/repository/UsersRepositoryExtImplTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/IamUserRegistrationServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/UserServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/registration/ExternalUserIdObfuscatorServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/registration/FiscalCodeObfuscatorServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/registration/UserRegistrationServiceTest.java

feat: P4ADEV-510 storingUsers

---

openapi/p4pa-auth.openapi.yaml
src/main/java/it/gov/pagopa/payhub/auth/dto/IamUserInfoDTO.java
src/main/java/it/gov/pagopa/payhub/auth/dto/IamUserOrganizationRolesDTO.java
src/main/java/it/gov/pagopa/payhub/auth/service/TokenStoreService.java
src/main/java/it/gov/pagopa/payhub/auth/service/TokenStoreServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/IDTokenClaims2UserInfoMapper.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/IamUserRegistrationService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/IamUserInfoDTO2UserInfoMapper.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserServiceImpl.java
src/test/java/it/gov/pagopa/payhub/auth/service/TokenStoreServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/IDTokenClaims2UserInfoMapperTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/IamUserRegistrationServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/UserServiceTest.java

fix: P4ADEV-642 separating UserInfo an iamUserInfo models

---

postman/p4pa-auth-E2E.postman_collection.json
src/main/java/it/gov/pagopa/payhub/auth/config/RedisConfig.java
src/main/java/it/gov/pagopa/payhub/auth/dto/IamUserInfoDTO.java
src/main/java/it/gov/pagopa/payhub/auth/exception/AuthExceptionHandler.java
src/main/java/it/gov/pagopa/payhub/auth/exception/custom/UserNotFoundException.java
src/main/java/it/gov/pagopa/payhub/auth/model/Operator.java
src/main/java/it/gov/pagopa/payhub/auth/model/User.java
src/main/java/it/gov/pagopa/payhub/auth/repository/OperatorsRepository.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/IamUserRegistrationService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/IamUserInfoDTO2UserInfoMapper.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserServiceImpl.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/IamUserRegistrationServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/IamUserInfoDTO2UserInfoMapperTest.java

fix: P4ADEV-634 userInfo will return Operator data from db

---

openapi/p4pa-auth.openapi.yaml
src/main/java/it/gov/pagopa/payhub/auth/service/user/IamUserInfoDTO2UserInfoMapper.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/IamUserInfoDTO2UserInfoMapperTest.java

fix: P4ADEV-651 adding mappedExternalUserId to UserInfo model

---

src/main/java/it/gov/pagopa/payhub/auth/service/user/registration/FiscalCodeObfuscatorService.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/registration/FiscalCodeObfuscatorServiceTest.java

fix: P4ADEV-636 userCode obfuscated

---

src/main/java/it/gov/pagopa/payhub/auth/service/user/retrieve/OperatorDTOMapper.java

fix: P4ADEV-671 fix missing @Service annotation

---

src/main/java/it/gov/pagopa/payhub/auth/repository/OperatorsRepository.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/retrieve/OrganizationOperatorRetrieverService.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/UserServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/retrieve/OrganizationOperatorRetrieverServiceTest.java

fix: P4ADEV-675 operator list pageable

---

src/main/java/it/gov/pagopa/payhub/auth/config/JsonConfig.java
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthnControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/repository/OperatorsRepository.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthnService.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthnServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzService.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/retrieve/OrganizationOperatorRetrieverService.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthnControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthnServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthzServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/UserServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/retrieve/OrganizationOperatorRetrieverServiceTest.java

feat: P4ADEV-676 controller2service

---

postman/p4pa-auth-E2E.postman_collection.json
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/security/JwtAuthenticationFilter.java

chore: P4ADEV-524 operator list postman test

---

src/main/java/it/gov/pagopa/payhub/auth/mypay/service/MyPayUsersService.java
src/main/java/it/gov/pagopa/payhub/auth/mypivot/service/MyPivotUsersService.java
src/test/java/it/gov/pagopa/payhub/auth/mypay/service/MyPayUsersServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/mypivot/service/MyPivotUsersServiceTest.java

fix: P4ADEV-514 fix insert mypay mypivot

---

postman/p4pa-auth-E2E.postman_collection.json

chore: P4ADEV-528 - add test Postman

---

openapi/p4pa-auth.openapi.yaml
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzService.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzServiceImpl.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerNoOrganizzationAccessModeTest.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthzServiceTest.java

chore: P4ADEV-525 expose createOrganizationOperator API

---

postman/p4pa-auth-NoAccessModeOrganization.postman_collection.json

chore: P4ADEV-526 - add test Postman

---

helm/values.yaml
src/main/java/it/gov/pagopa/payhub/auth/service/DataCipherService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/registration/ExternalUserIdObfuscatorService.java
src/main/java/it/gov/pagopa/payhub/auth/utils/HashAlgorithm.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/payhub/auth/service/DataCipherServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/registration/ExternalUserIdObfuscatorServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/utils/HastAlgorithmTest.java

fix: P4ADEV-637 obfuscate external user id

---

src/main/java/it/gov/pagopa/payhub/auth/repository/OperatorsRepositoryExtImpl.java
src/test/java/it/gov/pagopa/payhub/auth/repository/OperatorsRepositoryExtImplTest.java

fix: P4ADEV-802 refactor OperatorId

---

openapi/p4pa-auth.openapi.yaml
postman/p4pa-auth-E2E.postman_collection.json
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/exception/AuthExceptionHandler.java
src/main/java/it/gov/pagopa/payhub/auth/exception/custom/OperatorNotFoundException.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzService.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzServiceImpl.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthzServiceTest.java

chore: P4ADEV-878 expose API getOrganizationOperator

---

openapi/p4pa-auth.openapi.yaml
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/repository/UsersRepository.java
src/main/java/it/gov/pagopa/payhub/auth/repository/UsersRepositoryExt.java
src/main/java/it/gov/pagopa/payhub/auth/repository/UsersRepositoryExtImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzService.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzServiceImpl.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/repository/OperatorsRepositoryExtImplTest.java
src/test/java/it/gov/pagopa/payhub/auth/repository/UsersRepositoryExtImplTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthzServiceTest.java

fix: P4ADEV-737 expose queryParams to getOrganizationOperators API

---

postman/p4pa-auth-E2E.postman_collection.json

chore: P4ADEV-738_addTestPostman

---

src/main/java/it/gov/pagopa/payhub/auth/service/DataCipherService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/registration/ExternalUserIdObfuscatorService.java
src/test/java/it/gov/pagopa/payhub/auth/service/DataCipherServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/registration/ExternalUserIdObfuscatorServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/utils/HastAlgorithmTest.java

chore: P4ADEV-959 change obfuscate mappedexternaluserlogin from base64 to base64Url

---

.github/CODEOWNERS

fix: Code owners

---

.github/CODEOWNERS
openapi/p4pa-auth.openapi.yaml
postman/p4pa-auth-E2E.postman_collection.json
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/repository/UsersRepositoryExt.java
src/main/java/it/gov/pagopa/payhub/auth/repository/UsersRepositoryExtImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzService.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/DataCipherService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/registration/ExternalUserIdObfuscatorService.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/repository/OperatorsRepositoryExtImplTest.java
src/test/java/it/gov/pagopa/payhub/auth/repository/UsersRepositoryExtImplTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthzServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/DataCipherServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/registration/ExternalUserIdObfuscatorServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/utils/HastAlgorithmTest.java

feat: Release UAT

---

openapi/p4pa-auth.openapi.yaml
postman/p4pa-auth-NoAccessModeOrganization.postman_collection.json
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzService.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthzServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/retrieve/UserDTOMapper.java
src/main/java/it/gov/pagopa/payhub/auth/utils/SecurityUtils.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerNoOrganizzationAccessModeTest.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthzServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/user/retrieve/UserDTOMapperTest.java
src/test/java/it/gov/pagopa/payhub/auth/utils/SecurityUtilsTest.java

chore: P4ADEV-975 implement createUser API

---

src/main/java/it/gov/pagopa/payhub/auth/mypay/model/MyPayUser.java
src/main/java/it/gov/pagopa/payhub/auth/mypay/service/MyPayUsersService.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/registration/UserRegistrationService.java
src/test/java/it/gov/pagopa/payhub/auth/mypay/service/MyPayUsersServiceTest.java

feat: P4ADEV-986 refactor mygov user from MyPay

---

.devops/deploy-pipelines.yml

- added task to send message on slack in case of failing step in pipeline

chore: P4ADEV-902 added task send message on slack to pipeline

---

.github/workflows/config/trivy.yaml
.github/workflows/security-scan.yml
.github/workflows/send-notification.yml

chore: P4ADEV-1002_addSecurityScanToP4PA-AUTH

---

src/main/java/it/gov/pagopa/payhub/auth/service/DataCipherService.java

fix: P4ADEV-791 fixed typos

---

postman/p4pa-auth-E2E.postman_collection.json

fix: P4ADEV-1246_testpostman

---

openapi/p4pa-auth.openapi.yaml
src/main/java/it/gov/pagopa/payhub/auth/controller/AuthnControllerImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthnService.java
src/main/java/it/gov/pagopa/payhub/auth/service/AuthnServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateExternalTokenService.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthnControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthnServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateExternalTokenServiceTest.java

feat: P4ADEV-1247 apply new openApi version and maintain pre existing logics

---

postman/p4pa-auth-E2E.postman_collection.json

chore: P4ADEV-1246_testpostman

---

postman/p4pa-auth-E2E.postman_collection.json
src/main/java/it/gov/pagopa/payhub/auth/service/AuthnServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/a2a/ClientCredentialService.java
src/main/java/it/gov/pagopa/payhub/auth/service/a2a/ClientCredentialServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/a2a/ClientService.java
src/main/java/it/gov/pagopa/payhub/auth/service/a2a/ClientServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/a2a/ValidateClientCredentialsService.java
src/main/java/it/gov/pagopa/payhub/auth/service/a2a/retrieve/ClientRetrieverService.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenService.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateExternalTokenService.java
src/test/java/it/gov/pagopa/payhub/auth/service/AuthnServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/a2a/ClientCredentialsServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/a2a/ClientServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/a2a/ValidateClientCredentialsServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/a2a/retrieve/ClientRetrieverServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/exchange/ValidateExternalTokenServiceTest.java

feat: PROMOTE TO UAT

---

postman/p4pa-auth-E2E.postman_collection.json

chore: P4ADEV-1277-postman-test-activity

---

openapi/p4pa-auth.openapi.yaml
postman/p4pa-auth-E2E.postman_collection.json
src/main/java/it/gov/pagopa/payhub/auth/exception/AuthExceptionHandler.java
src/main/java/it/gov/pagopa/payhub/auth/exception/custom/M2MClientConflictException.java
src/main/java/it/gov/pagopa/payhub/auth/service/a2a/registration/ClientRegistrationService.java
src/test/java/it/gov/pagopa/payhub/auth/controller/AuthzControllerTest.java
src/test/java/it/gov/pagopa/payhub/auth/service/a2a/registration/ClientRegistrationServiceTest.java

fix: P4ADEV-1310 handling registerClient conflict

---

helm/values.yaml
src/main/java/it/gov/pagopa/payhub/auth/service/a2a/AuthorizeClientCredentialsRequestService.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/payhub/auth/service/a2a/AuthorizeClientCredentialsRequestServiceTest.java

feat: P4ADEV-1264-P4PA-AUTH-handle-client-credential-piattaforma-unitaria-via-env

---

build.gradle.kts
gradle.lockfile
src/main/java/it/gov/pagopa/payhub/auth/security/JwtAuthenticationFilter.java
src/main/java/it/gov/pagopa/payhub/auth/service/a2a/ClientCredentialServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/exchange/ExchangeTokenServiceImpl.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/IamUserInfoDTO2UserInfoMapper.java
src/main/java/it/gov/pagopa/payhub/auth/service/user/UserServiceImpl.java
src/main/resources/logback-spring.xml

feat: P4ADEV-1425 logging traceId and ExternalUserId

---

.devops/deploy-pipelines.yml

fix: postman env file

---

.devops/deploy-pipelines.yml

fix: PROMOTE UAT
